# Generated by Django 6.0.2 on 2026-04-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstame", models.CharField(max_length=50)),
                ("mobile", models.IntegerField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.IntegerField()),
            ],
        ),
    ]
