# Generated by Django 6.0.2 on 2026-04-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="firstame",
            new_name="firstname",
        ),
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.IntegerField(),
        ),
    ]
