# Generated by Django 6.0.2 on 2026-04-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_firstame_customer_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(),
        ),
    ]
