# Generated by Django 6.0.2 on 2026-04-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_addtocart"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="addtocart",
            new_name="Cart",
        ),
    ]
